//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanIEatHere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int AppUserID { get; set; }
        public string ASPUserID { get; set; }
        public string AppUserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public Nullable<int> DietaryRestrictionID1 { get; set; }
        public Nullable<int> DietaryRestrictionID2 { get; set; }
        public Nullable<int> DietaryRestrictionID3 { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DietaryRestriction DietaryRestriction { get; set; }
        public virtual DietaryRestriction DietaryRestriction1 { get; set; }
        public virtual DietaryRestriction DietaryRestriction2 { get; set; }
    }
}
