//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanIEatHere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public int FoodItemID { get; set; }
        public string FoodItemName { get; set; }
        public string ListIngredients { get; set; }
        public int FoodItemRating { get; set; }
        public int CourseID { get; set; }
        public int ReviewID { get; set; }
        public int DietaryRestrictionID { get; set; }
        public Nullable<int> DietaryRestrictionID2 { get; set; }
        public Nullable<int> DietaryRestrictionID3 { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual DietaryRestriction DietaryRestriction { get; set; }
        public virtual DietaryRestriction DietaryRestriction1 { get; set; }
        public virtual DietaryRestriction DietaryRestriction2 { get; set; }
        public virtual Review Review { get; set; }
    }
}
