//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanIEatHere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.FoodItems = new HashSet<FoodItem>();
        }
    
        public int ReviewID { get; set; }
        public string UserID { get; set; }
        public string NumFoodOptions { get; set; }
        public int NumFoodOptionsRating { get; set; }
        public string GeneralComments { get; set; }
        public int OverallRating { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int RestaurantID { get; set; }
        public int RestaurantPriceRating { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodItem> FoodItems { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
